package frc.robot.subsystems;

import frc.robot.Constants;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;



public class Drive extends SubsystemBase {

    private final DifferentialDrive robotDrive = Constants.robotDrive;


    public Drive() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

   
    

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }


    public void setDrive(double vY, double vRot) {
        robotDrive.arcadeDrive(vY, vRot);
    }


}

